version: '3.8'
services:
  api:
    build: ./apps/api
    ports:
      - "3000:3000"
    container_name: note-saver-api
    volumes:
      - ./apps/api/notes.json:/app/notes.json
  web:
    build: ./apps/web
    ports:
      - "8080:80"
    container_name: note-saver-web
    depends_on:
      - api
